# -*- coding: utf-8 -*-
"""HackerRank_Correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-8zehS1hbjmKCY7zeSyj-Ss-9ZY9KK5

# Importing Required Libraries
"""

import numpy as np
import pandas as pd
import scipy.stats

"""# Defining arrays using numpy"""

x=np.array([15,12,8,8,7,7,7,6,5,3])
y=np.array([10,25,17,11,13,17,20,13,9,15])

corr_coef = np.corrcoef(x,y)
print(corr_coef)

print(corr_coef[0,1])

"""# Pearson Coefficient - Scipy Correlation Calculation"""

r=scipy.stats.pearsonr(x,y)
r

"""# Rounding off to 3 decimal places"""

print(round(r[0],3), (round(r[1],3)))